{
  "header" : {
    "format" : "commit preview report",
    "version" : 2
  },
  "analysisInfo" : {
    "reportTimestamp" : "2015-04-07T02:22:06.332Z",
    "comparisonSnapshotId" : null,
    "ownerAssignmentRule" : "default_component_owner",
    "command" : "/usr/local/cov-analysis-7.6.0/bin/cov-analyze --dir /home/ps2white/coverity-idirs/g68-pipair -c /home/ps2white/coverity_config.xml --include-java -j auto --disable-webapp-security --strip-path /home/ps2white/qaproj/SE465-project/pi --all --enable-fb",
    "user" : "admin"
  },
  "issueInfo" : [ {
    "cid" : 10359,
    "mergeKey" : "bc9f437e8dec10c61c6831d1c051f726",
    "presentInComparisonSnapshot" : false,
    "firstDetectedDateTime" : "2015-04-07T01:46:06.803Z",
    "occurrences" : [ {
      "checker" : "MISSING_BREAK",
      "file" : "/usr/include/boost/format/parsing.hpp",
      "function" : "_ZN5boost2io6detail22parse_printf_directiveIcSt11char_traitsIcESaIcEN9__gnu_cxx17__normal_iteratorIPKcSsEESt5ctypeIcEEEbRT2_RKSD_PNS1_11format_itemIT_T0_T1_EERKT3_mh",
      "extra" : "88",
      "mergeWithLowercaseFile" : false,
      "subcategory" : "none",
      "mainEventLineNumber" : 260,
      "mainEventDescription" : "The case for value \"'X'\" is not terminated by a 'break' statement.",
      "componentName" : "Other",
      "componentDefaultOwner" : null,
      "componentDefaultOwnerLdapServer" : null
    } ],
    "triage" : {
      "externalReference" : null,
      "classification" : "Pending",
      "owner" : null,
      "action" : "Undecided",
      "severity" : "Unspecified",
      "fixTarget" : "Untargeted",
      "legacy" : "False"
    },
    "customTriage" : { },
    "ownerLdapServerName" : null
  }, {
    "cid" : 10360,
    "mergeKey" : "bcf57abe6184338a97d4a48aa4245a2c",
    "presentInComparisonSnapshot" : false,
    "firstDetectedDateTime" : "2015-04-07T01:46:06.803Z",
    "occurrences" : [ {
      "checker" : "MISSING_BREAK",
      "file" : "/usr/include/boost/format/parsing.hpp",
      "function" : "_ZN5boost2io6detail22parse_printf_directiveIcSt11char_traitsIcESaIcEN9__gnu_cxx17__normal_iteratorIPKcSsEESt5ctypeIcEEEbRT2_RKSD_PNS1_11format_itemIT_T0_T1_EERKT3_mh",
      "extra" : "102",
      "mergeWithLowercaseFile" : false,
      "subcategory" : "none",
      "mainEventLineNumber" : 283,
      "mainEventDescription" : "The case for value \"'f'\" is not terminated by a 'break' statement.",
      "componentName" : "Other",
      "componentDefaultOwner" : null,
      "componentDefaultOwnerLdapServer" : null
    } ],
    "triage" : {
      "externalReference" : null,
      "classification" : "Pending",
      "owner" : null,
      "action" : "Undecided",
      "severity" : "Unspecified",
      "fixTarget" : "Untargeted",
      "legacy" : "False"
    },
    "customTriage" : { },
    "ownerLdapServerName" : null
  }, {
    "cid" : 10361,
    "mergeKey" : "b58657261641eeb9212ad51bbe2a7b1e",
    "presentInComparisonSnapshot" : false,
    "firstDetectedDateTime" : "2015-04-07T01:46:06.803Z",
    "occurrences" : [ {
      "checker" : "UNCAUGHT_EXCEPT",
      "file" : "/pipair.cpp",
      "function" : "main",
      "extra" : "too_few_args",
      "mergeWithLowercaseFile" : false,
      "subcategory" : "none",
      "mainEventLineNumber" : 22,
      "mainEventDescription" : "In function \"main(int, char **)\" an exception of type \"boost::io::too_few_args const\" is thrown and never caught.",
      "componentName" : "Other",
      "componentDefaultOwner" : null,
      "componentDefaultOwnerLdapServer" : null
    } ],
    "triage" : {
      "externalReference" : null,
      "classification" : "Bug",
      "owner" : null,
      "action" : "Undecided",
      "severity" : "Unspecified",
      "fixTarget" : "Untargeted",
      "legacy" : "False"
    },
    "customTriage" : { },
    "ownerLdapServerName" : null
  }, {
    "cid" : 10362,
    "mergeKey" : "83f07aeb06f8b09c4100479bfbaed236",
    "presentInComparisonSnapshot" : false,
    "firstDetectedDateTime" : "2015-04-07T01:46:06.803Z",
    "occurrences" : [ {
      "checker" : "UNCAUGHT_EXCEPT",
      "file" : "/pipair.cpp",
      "function" : "main",
      "extra" : "too_many_args",
      "mergeWithLowercaseFile" : false,
      "subcategory" : "none",
      "mainEventLineNumber" : 22,
      "mainEventDescription" : "In function \"main(int, char **)\" an exception of type \"boost::io::too_many_args const\" is thrown and never caught.",
      "componentName" : "Other",
      "componentDefaultOwner" : null,
      "componentDefaultOwnerLdapServer" : null
    } ],
    "triage" : {
      "externalReference" : null,
      "classification" : "Bug",
      "owner" : null,
      "action" : "Undecided",
      "severity" : "Unspecified",
      "fixTarget" : "Untargeted",
      "legacy" : "False"
    },
    "customTriage" : { },
    "ownerLdapServerName" : null
  }, {
    "cid" : 10363,
    "mergeKey" : "67be7e15837d4465914493b675daa8ec",
    "presentInComparisonSnapshot" : false,
    "firstDetectedDateTime" : "2015-04-07T01:46:06.803Z",
    "occurrences" : [ {
      "checker" : "UNINIT",
      "file" : "/pipair.cpp",
      "function" : "main",
      "extra" : "current_function",
      "mergeWithLowercaseFile" : false,
      "subcategory" : "pointer_deref_read",
      "mainEventLineNumber" : 42,
      "mainEventDescription" : "Using uninitialized value \"current_function\".",
      "componentName" : "Other",
      "componentDefaultOwner" : null,
      "componentDefaultOwnerLdapServer" : null
    } ],
    "triage" : {
      "externalReference" : null,
      "classification" : "Intentional",
      "owner" : null,
      "action" : "Undecided",
      "severity" : "Unspecified",
      "fixTarget" : "Untargeted",
      "legacy" : "False"
    },
    "customTriage" : { },
    "ownerLdapServerName" : null
  } ]
}